export const sampleResponse = `
# Summary (Heading)  \nThis document provides an overview of the workflow related to Azure Logic Apps. The workflow contains several steps including triggers, actions, and iterations. It involves initializing variables, performing actions on variables, and iterating through a collection.\n\n||Workflow Properties|Value|  \n|-----|-----|-----|  \n|1|Workflow kind|N/A|  \n|2|Connector type - In App|5|  \n|3|Connector type - Shared|0|  \n|4|Connector type - Custom|0|  \n|5|API Connections|0|  \n\n# Workflow Steps  \n## How the workflow starts (Triggers)  \n- **manual**  \n   - Type: N/A  \n   - Description: This operation is a manual trigger that starts the workflow. \n\n## How the workflow continues (Actions)  \n- **Initialize_variable**  \n   - Type: In App  \n   - Description: This operation initializes a variable for use in the workflow.  \n   - Actions Inputs: {\n    'variables': [\n        {\n            'name': 'var1',\n            'type': 'integer'\n        }\n    ]\n} \n\n- **Response**  \n   - Type: N/A  \n   - Description: This operation generates a response with the value of the variable.  \n   - Actions Inputs: {\n    'statusCode': 200,\n    'body': '@variables('var1')'\n} \n\n- **Foreach**  \n    - Summary: This block iterates through a collection.  \n   - Type: N/A  \n   - Description: This operation performs actions on each item in the collection.  \n   - Actions:  \n       - **Increment_variable_2**  \n           - Type: N/A  \n           - Description: This operation increments the value of the variable by 1.  \n           - Actions Inputs: {\n    'name': 'var1',\n    'value': 1\n} \n\n       - **Increment_variable_3**  \n            - Type: N/A  \n            - Description: This operation increments the value of the variable by 1.  \n            - Actions Inputs: {\n    'name': 'var1',\n    'value': 1\n} \n\n       - **Foreach_nested**  \n            - Summary: This block is nested within the foreach loop.  \n            - Type: N/A  \n            - Description: This operation performs actions on each item in the nested collection.  \n            - Actions:  \n                - **Increment_variable_4**  \n                    - Type: N/A  \n                    - Description: This operation increments the value of the variable by 1.  \n                    - Actions Inputs: {\n    'name': 'var1',\n    'value': 1\n} \n\n                - **Increment_variable_5**  \n                    - Type: N/A  \n                    - Description: This operation increments the value of the variable by 1.  \n                    - Actions Inputs: {\n    'name': 'var1',\n    'value': 1\n} \n\n- **Foreach_empty**  \n    - Summary: This block is executed if the collection is empty.  \n    - Type: N/A  \n    - Description: This operation performs actions when the collection is empty.  \n    - Actions:  \n    .

`;

export const formatResponseToMarkdown = (response: string) => {
  // const formattedResponse = response.replace(new RegExp(/\n/,'g'), '  \n')
  // console.log(formattedResponse)
  return response;
};
